### ISSUE TITLE
Rain Sensor Interface

### ISSUE THREAD

**Issue by mikeshams** [Group-1-winter-2021/ESE4009_2#3]
Ajay - What issues did you face? How to resolve?

**Comment by capstonepro** [comment]
Interfacing for the rain detection module with the beagleboneblack wireless is hard at first as you dont get any references to work it with the beaglebone black wireless .
so i found the link https://www.element14.com/community/community/designcenter/single-board-computers/next-genbeaglebone/blog/2019/08/15/beaglebone-black-bbb-io-gpio-spi-and-i2c-library-for-c-2019-edition#jive_content_id_How_to_Install_the_Library
where i have downloaded the library for gpio pins so that i can use the gpio pins for interfacing the rain drop sensor module 
so for rain drop sensor module i found the reference it with the raspberry pi 
https://raspi.tv/2017/make-a-rain-alert-system-with-raspberry-pi
so after developing the code while compiling the code through gcc compiler one should also add -liobb at the end to not give ny errors
so those are some issues i faced while interfacing .
